export const index = "/";
export const logIn = "/auth/login";
export const verify = "/auth/verify";
export const signUp = "/auth/signup";
export const forgotPass = "/auth/forgot-pass";
export const events = "/events";
export const notes = "/notes";
export const subjectNotes = "/notes/:subjectId";
export const physicsChapters = "/notes/physics/chapters";
export const notesChapter = "/notes/chapter/:chapterId";
export const notesViewer = "/notes/viewer/:noteId";
export const boardReady = "/board-ready";
export const quiz = "/quiz";
export const quizCreate = "/quiz/create";
export const quizTake = "/quiz/attempt/:attemptId";
export const quizResults = "/quiz/results/:attemptId";
export const quizHistory = "/quiz/history";
export const profile = "/profile";
export const importantQuestions = "/important-questions";
export const ncertSolutions = "/ncert-solutions";
export const ncertExemplar = "/ncert-exemplar";
export const books = "/books";
export const chat = "/chat";
export const videoLearning = "/video-learning";
export const videoLearningSubject = "/video-learning/:subjectId"; // e.g. /video-learning/maths
export const videoLearningContent = "/video-learning/:subjectId/:contentId"; // e.g. /video-learning/science/physics OR /video-learning/maths/real-numbers
export const videoLearningChapter = "/video-learning/:subjectId/:branchId/:chapterId";
export const videoWatchMaths = "/video-learning/watch/:subjectId/:chapterId/:videoId";
export const videoWatchScience = "/video-learning/watch/:subjectId/:branchId/:chapterId/:videoId";
export const courses = "/courses";
export const myCourses = "/my-courses";
export const courseLearning = "/course/:courseId/learn";
export const liveClassHost = "/live-class/:classId/host";
export const notifications = "/notifications";
export const supportTickets = "/support-tickets";
export const privacyPolicy = "/privacy-policy";
export const termsOfService = "/terms-of-service";
export const refundPolicy = "/refund-policy";
export const masteryHub = "/mastery-hub";
export const masterySet = "/mastery-hub/set/:setId";

// Admin routes
export const adminLogin = "/admin/login";
export const adminSignup = "/admin/signup";
export const adminRequestStatus = "/admin/request-status";
export const adminForgotPassword = "/admin/forgot-password";
export const adminDashboard = "/admin/dashboard";
export const adminUserAnalytics = "/admin/users/:userId/analytics";